
" vunlde.vimで管理してるpluginを読み込む
source ~/dotfiles_deprecated/vim/vimrc.bundle

" 基本設定
source ~/dotfiles_deprecated/vim/vimrc.basic

" StatusLine設定
source ~/dotfiles_deprecated/vim/vimrc.statusline

" インデント設定
source ~/dotfiles_deprecated/vim/vimrc.indent

" 表示関連
source ~/dotfiles_deprecated/vim/vimrc.apperance

" 補完関連
source ~/dotfiles_deprecated/vim/vimrc.completion

" Tags関連
" source ~/dotfiles_deprecated/vim/.vimrc.tags

" 検索関連
source ~/dotfiles_deprecated/vim/vimrc.search

" 移動関連
source ~/dotfiles_deprecated/vim/vimrc.moving

" Color関連
source ~/dotfiles_deprecated/vim/vimrc.colors

" 編集関連
source ~/dotfiles_deprecated/vim/vimrc.editing

" エンコーディング関連
source ~/dotfiles_deprecated/vim/vimrc.encoding

" その他
source ~/dotfiles_deprecated/vim/vimrc.misc

" プラグインに依存するアレ
" if has('gui_macvim')
source ~/dotfiles_deprecated/vim/vimrc.plugins_setting
" endif

"Vimでgitのログをきれいに表示する - derisの日記
"  http://deris.hatenablog.jp/entry/2013/05/10/003430
" source ~/dotfiles_deprecated/vim/.vimrc.gitlogviewer

